language: php

env:
  - COMPOSER_PATCH=default
  - COMPOSER_PATCH=2.2
  - COMPOSER_PATCH=2.3
  - COMPOSER_PATCH=minimal

php:
  - 5.5
  - 5.6
  - 7

before_script:
  - "php tests/prepare-composer.php"
  - composer self-update
  - composer install --no-interaction --prefer-source
  - ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .
  - mysql -e 'create database php_test_suite_test collate utf8_general_ci;'

script: ./tests/run-tests.sh

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
